from . import test_pppoe_refresh_mac
from . import test_pppoe_multisession
from . import test_isp_dashboard
from . import test_isp_billing_policy
from . import test_isp_payment_whatsapp
from . import test_isp_phone_parser
from . import test_isp_brimo_ocr
from . import test_isp_payment_verify
from . import test_isp_fonnte_inbound
from . import test_isp_radius
from . import test_isp_wa_register
from . import test_isp_wa_billing_confirm
from . import test_isp_pppoe_profile_pool
