sql {
    dialect = "postgresql"
    driver = "rlm_sql_postgresql"
    server = "$ENV{RADIUS_DB_HOST}"
    port = $ENV{RADIUS_DB_PORT}
    login = "$ENV{RADIUS_DB_USER}"
    password = "$ENV{RADIUS_DB_PASSWORD}"
    radius_db = "$ENV{RADIUS_DB_NAME}"

    acct_table1 = "radacct"
    acct_table2 = "radacct"
    postauth_table = "radpostauth"
    authcheck_table = "radcheck"
    authreply_table = "radreply"
    groupcheck_table = "radgroupcheck"
    groupreply_table = "radgroupreply"
    usergroup_table = "radusergroup"

    read_groups = yes
    delete_stale_sessions = yes
    read_clients = yes
    nas_table = "nas"
    pool {
        start = 1
        min = 1
        max = 8
        spare = 1
        idle_timeout = 60
    }
    $INCLUDE ${modconfdir}/sql/main/${dialect}/queries.conf
}
