[options]
admin_passwd = dktisp
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/enterprise,/mnt/extra-addons/dkt
http_port = 8069
list_db = True
dbfilter =
server_wide_modules = web
proxy_mode = False
limit_time_cpu = 1800
limit_time_real = 1800
without_demo = True
