from . import isp_phone
from . import res_partner
from . import isp_area
from . import isp_package
from . import isp_package_area_price
from . import isp_cpe
from . import isp_cpe_pppoe_history
from . import isp_subscription
from . import isp_installation_type
from . import isp_installation_fee
from . import isp_device_history
from . import isp_subscription_template
from . import isp_mikrotik
from . import isp_mikrotik_profile
from . import isp_pppoe_profile_template
from . import isp_radius
from . import isp_discount
from . import isp_report
from . import account_move
from . import isp_installation_wizard
from . import isp_dashboard
from . import isp_payment_proof
from . import isp_whatsapp_message
from . import isp_whatsapp_template
from . import isp_wa_registration
from . import res_users
from . import res_config_settings 