{
    'name': 'DKT ISP Billing',
    'version': '1.0',
    'category': 'Services/ISP',
    'summary': 'Modul billing untuk ISP',
    'description': """
        Modul billing untuk ISP dengan fitur:
        - Manajemen pelanggan
        - Manajemen layanan
        - Manajemen perangkat
        - Billing dan invoice
        - Integrasi dengan Mikrotik
    """,
    'author': 'PT. Digital Kreasi Teknologi',
    'website': 'https://dkt.co.id',
    'depends': [
        'base',
        'mail',
        'account',
        'account_accountant',
        'account_asset',
        'product',
        'uom',
        'sale',
        'sale_management',
        'sale_subscription',
        'portal',
        'web_cohort',
        'rating',
        'base_automation',
        'sms',
        'l10n_id',
    ],
    'data': [
        'security/isp_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/account_data.xml',
        'data/subscription_data.xml',
        'data/product_data.xml',
        'data/uom_data.xml',
        'data/master_data.xml',
        'views/isp_mikrotik_views.xml',
        'views/isp_mikrotik_profile_views.xml',
        'views/isp_package_views.xml',
        'views/isp_installation_type_views.xml',
        'views/isp_installation_fee_views.xml',
        'views/isp_device_history_views.xml',
        'views/isp_subscription_template_views.xml',
        'views/isp_cpe_views.xml',
        'views/isp_subscription_views.xml',
        'views/isp_discount_views.xml',
        'views/isp_report_views.xml',
        'views/isp_invoice_views.xml',
        'views/isp_installation_wizard_views.xml',
        'views/res_partner_views.xml',
        'reports/isp_report_templates.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
} 